// Elementos da missão
export const alvos = {
  resgatar: [
    "criança",
    "camponês",
    "ferreiro",
    "mercador",
    "caçador",
    "mago iniciante",
    "curandeiro",
    "vendedora",
    "apotecário",
    "soldado ferido",
    "carpinteiro",
    "padeiro",
    "lavrador",
    "escrivão",
    "bibliotecário",
    "homem do campo",
    "mestre de campo",
    "pastor",
    "mestre de ervas",
    "artesão",
    "vigarista",
    "mestre de ferros",
    "trovador",
    "mulher grávida",
    "cozinheira",
    "pequeno nobre",
    "jovem aprendiz",
    "curandeiro ancião",
    "ancião da aldeia",
    "herdeiro perdido",
    "pescador",
    "poetisa",
    "pescador perdido",
    "garoto fugitivo",
    "músico",
    "arborista",
  ],
  matar: [
    "esqueleto",
    "goblin",
    "orc",
    "bandido",
    "bandidos",
    "criminosos",
    "assaltantes",
    "ladrões",
    "golpistas",
    "zumbi",
    "ratos",
    "aranha venenosa",
    "rato gigante",
    "lobo selvagem",
    "besta do mato",
    "javali selvagem",
    "serpente venenosa",
    "corvo hostil",
    "vaca zumbi",
    "lagarto mutante",
    "mosca gigante",
  ],
  coletar: [
    "ervas medicinais",
    "frutas silvestres",
    "pedras pequenas",
    "sementes comuns",
    "poeira de elfo",
    "flores do campo",
    "cogumelos comestíveis",
    "galhos secos",
    "pedaços de madeira",
    "ramos de flor",
    "raízes curativas",
    "pedras preciosas pequenas",
    "frutas tropicais",
    "plumas de aves",
    "casca de árvore",
    "folhas mágicas",
    "bagas do bosque",
    "pedaços de cristal",
    "fios de teia de aranha gigante",
    "pelos de lobo",
    "cordas do campo",
    "sementes raras",
    "bolotas de carvalho",
    "casulos de insetos",
    "seiva de árvore",
    "excrementos de criaturas",
    "pedaços de corais",
    "gotas de orvalho",
    "pó de fada",
    "escamas de peixe",
    "larvas mágicas",
    "sementes de flores raras",
  ],
};
